
imports:
    - { resource: ckfinder_config.php }
ckfinder:
    connector:
        licenseName: 'http://127.0.0.1:8000'
        licenseKey: '*5?7-*1**-M**Q-*N**-*7**-W*Q*-2**K'
        authenticationClass: App\CustomCKFinderAuth\CustomCKFinderAuth

        resourceTypes:
            MyResource:
                name: MyResource
                backend: default
                directory: myResource