knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/bin/wkhtmltopdf 
        options:    
            disable-javascript: true
            no-background: true
            encoding: UTF-8
    image:
        enabled:    true
        binary:     /usr/bin/wkhtmltoimage
        options:    []