sonata_admin:
    title: 'Cgofficiel Admin'
    assets:
        extra_javascripts:
            # ...
            - bundles/fosckeditor/ckeditor.js
            - bundles/sonataformatter/vendor/markitup-markitup/markitup/jquery.markitup.js
            - bundles/sonataformatter/markitup/sets/markdown/set.js
            - bundles/sonataformatter/markitup/sets/html/set.js
            - bundles/sonataformatter/markitup/sets/textile/set.js

        extra_stylesheets:
            # ...
            - bundles/sonataformatter/markitup/skins/sonata/style.css
            - bundles/sonataformatter/markitup/sets/markdown/style.css
            - bundles/sonataformatter/markitup/sets/html/style.css
            - bundles/sonataformatter/markitup/sets/textile/style.css
            - build/admin/css/style.css
            
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            tableaudebord:
                label: TABLEAU DE BORD
            facture:
                label: FACTURE
            configuration:
                label: CONFIGURATION
            tarifs:
                label: TARIFS
            users:
                label: UTILISATEURS
            notification:
                label: NOTIFICATION
            documents:
                label: DOCUMENTS
            transactions:
                label: TRANSACTIONS
                

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
