sonata_admin:
    title: 'Cgofficiel Admin'
    assets:
        extra_stylesheets:
            - build/style.css
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            tableaudebord:
                label: TABLEAU DE BORD
            facture:
                label: FACTURE
            configuration:
                label: CONFIGURATION
            tarifs:
                label: TARIFS
            users:
                label: UTILISATEURS
            notification:
                label: NOTIFICATION
            documents:
                label: DOCUMENTS
            transactions:
                label: TRANSACTIONS
                

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
