tlconseil_systempay:
    # Credentials
    site_id: 21275319
    # Keys
    key_dev: DQt3GlS3jxxhtRzO
    action_mode: INTERACTIVE
    # key_prod: XXXXX
    # Return
    url_return: http://dev2.cgofficiel.fr/payment/verification
    # Debug values : ON / OFF
    debug: ON
    # Return mode
    return_mode: POST
    # Possible values for ctx_mode : TEST / PRODUCTION
    ctx_mode: TEST
    # Language
    language: fr
    # Success
    redirect_success_timeout: 1
    redirect_success_message: http://dev2.cgofficiel.fr/payment/verification
    # Error
    redirect_error_timeout: 1
    redirect_error_message: http://dev2.cgofficiel.fr/payment/verification