easy_admin:
    design:
        menu:
            - {label: 'Blog', icon: 'newspaper-o'}
            - {entity: 'Article', icon: 'inbox', label: 'Articles'}
            - {entity: 'Categorie', icon: 'tags', label: 'Catégories'}
            - {entity: 'Faq', icon: 'comments', label: 'Faq'}
            - {entity: 'Commentaire', icon: 'warning', label: 'Commentaires'}