<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190616204030 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE ancientitulaire CHANGE raisonsociale raisonsociale VARCHAR(255) DEFAULT NULL, CHANGE nomprenom nomprenom VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE tarifs_prestations CHANGE commande_id commande_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE divn CHANGE demande_id demande_id INT DEFAULT NULL, CHANGE acquerreur_id acquerreur_id INT DEFAULT NULL, CHANGE file_id file_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE fos_user CHANGE client_id client_id INT DEFAULT NULL, CHANGE salt salt VARCHAR(255) DEFAULT NULL, CHANGE last_login last_login DATETIME DEFAULT NULL, CHANGE confirmation_token confirmation_token VARCHAR(180) DEFAULT NULL, CHANGE password_requested_at password_requested_at DATETIME DEFAULT NULL, CHANGE register_date register_date DATETIME DEFAULT NULL, CHANGE france_connect_id france_connect_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE car_info CHANGE commande_id commande_id INT DEFAULT NULL, CHANGE marque marque VARCHAR(255) DEFAULT NULL, CHANGE model model VARCHAR(255) DEFAULT NULL, CHANGE serial_number serial_number VARCHAR(255) DEFAULT NULL, CHANGE color color VARCHAR(255) DEFAULT NULL, CHANGE nb_place nb_place VARCHAR(255) DEFAULT NULL, CHANGE horse_power horse_power VARCHAR(255) DEFAULT NULL, CHANGE version version VARCHAR(255) DEFAULT NULL, CHANGE vin vin VARCHAR(255) DEFAULT NULL, CHANGE horse_power_fiscal horse_power_fiscal VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE history_transaction CHANGE demande_id demande_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE fichier CHANGE demande_id demande_id INT DEFAULT NULL, CHANGE client_id client_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE valide_le valide_le DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE adresse CHANGE titulaire_id titulaire_id INT DEFAULT NULL, CHANGE vehicules_id vehicules_id INT DEFAULT NULL, CHANGE client_id client_id INT DEFAULT NULL, CHANGE numero numero INT DEFAULT NULL, CHANGE extension extension VARCHAR(255) DEFAULT NULL, CHANGE adprecision adprecision VARCHAR(255) DEFAULT NULL, CHANGE complement complement VARCHAR(255) DEFAULT NULL, CHANGE lieudit lieudit VARCHAR(255) DEFAULT NULL, CHANGE codepostal codepostal VARCHAR(255) DEFAULT NULL, CHANGE ville ville VARCHAR(255) DEFAULT NULL, CHANGE boitepostale boitepostale VARCHAR(255) DEFAULT NULL, CHANGE pays pays VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE ctvo CHANGE demande_id demande_id INT DEFAULT NULL, CHANGE ancien_titulaire_id ancien_titulaire_id INT DEFAULT NULL, CHANGE acquerreur_id acquerreur_id INT DEFAULT NULL, CHANGE file_id file_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE new_titulaire CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE raison_sociale raison_sociale VARCHAR(255) DEFAULT NULL, CHANGE societe_commerciale societe_commerciale TINYINT(1) DEFAULT NULL, CHANGE siren siren VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cotitulaires CHANGE carte_grise_id carte_grise_id INT DEFAULT NULL, CHANGE divn_id divn_id INT DEFAULT NULL, CHANGE ctvo_id ctvo_id INT DEFAULT NULL, CHANGE type_cotitulaire type_cotitulaire VARCHAR(255) DEFAULT NULL, CHANGE raison_social_cotitulaire raison_social_cotitulaire VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE taxes CHANGE commande_id commande_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE duplicata CHANGE titulaire_id titulaire_id INT DEFAULT NULL, CHANGE demande_id demande_id INT DEFAULT NULL, CHANGE file_id file_id INT DEFAULT NULL, CHANGE demande_changement_titulaire demande_changement_titulaire TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE changement_adresse CHANGE nouveaux_titulaire_id nouveaux_titulaire_id INT DEFAULT NULL, CHANGE ancien_adresse_id ancien_adresse_id INT DEFAULT NULL, CHANGE file_id file_id INT DEFAULT NULL, CHANGE demande_id demande_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_changement_adresse CHANGE recto_verso_carte_grise recto_verso_carte_grise VARCHAR(255) DEFAULT NULL, CHANGE demande_certificat_immatriculation demande_certificat_immatriculation VARCHAR(255) DEFAULT NULL, CHANGE piece_identite_valid piece_identite_valid VARCHAR(255) DEFAULT NULL, CHANGE copie_attestation_assurance_valide copie_attestation_assurance_valide VARCHAR(255) DEFAULT NULL, CHANGE copie_permis_conduire copie_permis_conduire VARCHAR(255) DEFAULT NULL, CHANGE justificatif_domicile justificatif_domicile VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_cession CHANGE formulaire_cerfa_remplis formulaire_cerfa_remplis VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_duplicata CHANGE recto_verso_carte_grise recto_verso_carte_grise VARCHAR(255) DEFAULT NULL, CHANGE certificat_immatriculation certificat_immatriculation VARCHAR(255) DEFAULT NULL, CHANGE declarationde_perte_ou_vol declarationde_perte_ou_vol VARCHAR(255) DEFAULT NULL, CHANGE copie_controle_technique_en_cours_validite copie_controle_technique_en_cours_validite VARCHAR(255) DEFAULT NULL, CHANGE piece_identite_valid piece_identite_valid VARCHAR(255) DEFAULT NULL, CHANGE copie_attestation_assurance_valide copie_attestation_assurance_valide VARCHAR(255) DEFAULT NULL, CHANGE permis_de_conduire_du_titulaire permis_de_conduire_du_titulaire VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_ctvo CHANGE files_id files_id INT DEFAULT NULL, CHANGE recto_verso_carte_grise recto_verso_carte_grise VARCHAR(255) DEFAULT NULL, CHANGE declatation_cession declatation_cession VARCHAR(255) DEFAULT NULL, CHANGE demande_certificat demande_certificat VARCHAR(255) DEFAULT NULL, CHANGE piece_identite piece_identite VARCHAR(255) DEFAULT NULL, CHANGE copie_controle_technique copie_controle_technique VARCHAR(255) DEFAULT NULL, CHANGE copie_attestation_assurance copie_attestation_assurance VARCHAR(255) DEFAULT NULL, CHANGE copie_permis_conduire_titulaire copie_permis_conduire_titulaire VARCHAR(255) DEFAULT NULL, CHANGE justificatif_domicile justificatif_domicile VARCHAR(255) DEFAULT NULL, CHANGE procuration_mandat procuration_mandat VARCHAR(255) DEFAULT NULL, CHANGE recepisse_demande_achat recepisse_demande_achat VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_ivn CHANGE original_certificat_conformite_europeen original_certificat_conformite_europeen VARCHAR(255) DEFAULT NULL, CHANGE certificat_vente_original_facture_achat certificat_vente_original_facture_achat VARCHAR(255) DEFAULT NULL, CHANGE piece_identite_valid piece_identite_valid VARCHAR(255) DEFAULT NULL, CHANGE copie_attestation_assurance_valide copie_attestation_assurance_valide VARCHAR(255) DEFAULT NULL, CHANGE copie_permis_conduire_titulaire copie_permis_conduire_titulaire VARCHAR(255) DEFAULT NULL, CHANGE demande_original_certificat_immatriculation demande_original_certificat_immatriculation VARCHAR(255) DEFAULT NULL, CHANGE procuration_par_mandat procuration_par_mandat VARCHAR(255) DEFAULT NULL, CHANGE justificatif_domicile_recent justificatif_domicile_recent VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE files CHANGE demande_id demande_id INT DEFAULT NULL, CHANGE demande_duplicata_id demande_duplicata_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE user_infos CHANGE cession_acheteur_id cession_acheteur_id INT DEFAULT NULL, CHANGE cession_vendeur_id cession_vendeur_id INT DEFAULT NULL, CHANGE adresse_id adresse_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE commande CHANGE demarche_id demarche_id INT DEFAULT NULL, CHANGE demande_id demande_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE vehicule CHANGE vehicule_ancientitulaire_id vehicule_ancientitulaire_id INT DEFAULT NULL, CHANGE vehicule_cartegrise_id vehicule_cartegrise_id INT DEFAULT NULL, CHANGE vehicule_demande_id vehicule_demande_id INT DEFAULT NULL, CHANGE vehicule_client_id vehicule_client_id INT DEFAULT NULL, CHANGE client_id client_id INT DEFAULT NULL, CHANGE titulaire_id titulaire_id INT DEFAULT NULL, CHANGE numformule numformule VARCHAR(255) DEFAULT NULL, CHANGE datecg datecg DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE transaction CHANGE demande_id demande_id INT DEFAULT NULL, CHANGE amount amount INT DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE transaction_id transaction_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE configuration CHANGE dc dc TINYINT(1) DEFAULT NULL, CHANGE dca dca TINYINT(1) DEFAULT NULL, CHANGE dup dup TINYINT(1) DEFAULT NULL, CHANGE ctvo ctvo TINYINT(1) DEFAULT NULL, CHANGE divn divn TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE cartegrise CHANGE typevehicule typevehicule VARCHAR(255) DEFAULT NULL, CHANGE cgdepartement cgdepartement VARCHAR(255) DEFAULT NULL, CHANGE modele modele VARCHAR(255) DEFAULT NULL, CHANGE energie energie VARCHAR(255) DEFAULT NULL, CHANGE cv cv INT DEFAULT NULL, CHANGE datecirculation datecirculation DATE DEFAULT NULL, CHANGE co2 co2 INT DEFAULT NULL, CHANGE ptac ptac INT DEFAULT NULL');
        $this->addSql('ALTER TABLE client CHANGE client_contact_id client_contact_id INT DEFAULT NULL, CHANGE client_adresse_id client_adresse_id INT DEFAULT NULL, CHANGE client_nom_usage client_nom_usage VARCHAR(255) DEFAULT NULL, CHANGE client_dpt_naissance client_dpt_naissance VARCHAR(255) DEFAULT NULL, CHANGE client_pays_naissance client_pays_naissance VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cession CHANGE demande_id demande_id INT DEFAULT NULL, CHANGE file_id file_id INT DEFAULT NULL, CHANGE vendeur_id vendeur_id INT DEFAULT NULL, CHANGE acheteur_id acheteur_id INT DEFAULT NULL, CHANGE date_cession date_cession DATETIME DEFAULT NULL, CHANGE date_heure_de_la_vente date_heure_de_la_vente DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE documents CHANGE fichier_id fichier_id INT DEFAULT NULL, CHANGE type_demande_id type_demande_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE demande CHANGE ctvo_id ctvo_id INT DEFAULT NULL, CHANGE duplicata_id duplicata_id INT DEFAULT NULL, CHANGE divn_id divn_id INT DEFAULT NULL, CHANGE cession_id cession_id INT DEFAULT NULL, CHANGE changement_adresse_id changement_adresse_id INT DEFAULT NULL, CHANGE transaction_id transaction_id INT DEFAULT NULL, CHANGE statut_demande statut_demande VARCHAR(999) DEFAULT NULL, CHANGE paiement_demande paiement_demande VARCHAR(255) DEFAULT NULL, CHANGE tms_id_demande tms_id_demande INT DEFAULT NULL, CHANGE progression_demande progression_demande VARCHAR(999) DEFAULT NULL, CHANGE prix prix DOUBLE PRECISION DEFAULT NULL, CHANGE nomfic nomfic VARCHAR(255) DEFAULT NULL, CHANGE status_doc status_doc VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE contact CHANGE contact_telfixe contact_telfixe VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE financial_transactions CHANGE credit_id credit_id INT DEFAULT NULL, CHANGE payment_id payment_id INT DEFAULT NULL, CHANGE extended_data extended_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:extended_payment_data)\', CHANGE reason_code reason_code VARCHAR(100) DEFAULT NULL, CHANGE reference_number reference_number VARCHAR(100) DEFAULT NULL, CHANGE response_code response_code VARCHAR(100) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE tracking_id tracking_id VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE payment_instructions CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE credits CHANGE payment_id payment_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE payments CHANGE expiration_date expiration_date DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE adresse CHANGE client_id client_id INT DEFAULT NULL, CHANGE titulaire_id titulaire_id INT DEFAULT NULL, CHANGE vehicules_id vehicules_id INT DEFAULT NULL, CHANGE numero numero INT DEFAULT NULL, CHANGE extension extension VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE adprecision adprecision VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE complement complement VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE lieudit lieudit VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE codepostal codepostal VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE ville ville VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE boitepostale boitepostale VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE pays pays VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE ancientitulaire CHANGE raisonsociale raisonsociale VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE nomprenom nomprenom VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE car_info CHANGE commande_id commande_id INT DEFAULT NULL, CHANGE marque marque VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE model model VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE serial_number serial_number VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE color color VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE nb_place nb_place VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE horse_power horse_power VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE horse_power_fiscal horse_power_fiscal VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE version version VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE vin vin VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE cartegrise CHANGE typevehicule typevehicule VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE cgdepartement cgdepartement VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE modele modele VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE energie energie VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE cv cv INT DEFAULT NULL, CHANGE datecirculation datecirculation DATE DEFAULT \'NULL\', CHANGE co2 co2 INT DEFAULT NULL, CHANGE ptac ptac INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cession CHANGE demande_id demande_id INT DEFAULT NULL, CHANGE vendeur_id vendeur_id INT DEFAULT NULL, CHANGE acheteur_id acheteur_id INT DEFAULT NULL, CHANGE file_id file_id INT DEFAULT NULL, CHANGE date_heure_de_la_vente date_heure_de_la_vente DATETIME DEFAULT \'NULL\', CHANGE date_cession date_cession DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE changement_adresse CHANGE nouveaux_titulaire_id nouveaux_titulaire_id INT DEFAULT NULL, CHANGE ancien_adresse_id ancien_adresse_id INT DEFAULT NULL, CHANGE file_id file_id INT DEFAULT NULL, CHANGE demande_id demande_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE client CHANGE client_contact_id client_contact_id INT DEFAULT NULL, CHANGE client_adresse_id client_adresse_id INT DEFAULT NULL, CHANGE client_nom_usage client_nom_usage VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE client_dpt_naissance client_dpt_naissance VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE client_pays_naissance client_pays_naissance VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE commande CHANGE demarche_id demarche_id INT DEFAULT NULL, CHANGE demande_id demande_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE configuration CHANGE dc dc TINYINT(1) DEFAULT \'NULL\', CHANGE dca dca TINYINT(1) DEFAULT \'NULL\', CHANGE dup dup TINYINT(1) DEFAULT \'NULL\', CHANGE ctvo ctvo TINYINT(1) DEFAULT \'NULL\', CHANGE divn divn TINYINT(1) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE contact CHANGE contact_telfixe contact_telfixe VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE cotitulaires CHANGE carte_grise_id carte_grise_id INT DEFAULT NULL, CHANGE divn_id divn_id INT DEFAULT NULL, CHANGE ctvo_id ctvo_id INT DEFAULT NULL, CHANGE type_cotitulaire type_cotitulaire VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE raison_social_cotitulaire raison_social_cotitulaire VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE credits CHANGE payment_id payment_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE ctvo CHANGE demande_id demande_id INT DEFAULT NULL, CHANGE ancien_titulaire_id ancien_titulaire_id INT DEFAULT NULL, CHANGE acquerreur_id acquerreur_id INT DEFAULT NULL, CHANGE file_id file_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE demande CHANGE ctvo_id ctvo_id INT DEFAULT NULL, CHANGE duplicata_id duplicata_id INT DEFAULT NULL, CHANGE divn_id divn_id INT DEFAULT NULL, CHANGE cession_id cession_id INT DEFAULT NULL, CHANGE changement_adresse_id changement_adresse_id INT DEFAULT NULL, CHANGE transaction_id transaction_id INT DEFAULT NULL, CHANGE statut_demande statut_demande VARCHAR(999) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE paiement_demande paiement_demande VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE tms_id_demande tms_id_demande INT DEFAULT NULL, CHANGE progression_demande progression_demande VARCHAR(999) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE prix prix DOUBLE PRECISION DEFAULT \'NULL\', CHANGE nomfic nomfic VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE status_doc status_doc VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE demande_cession CHANGE formulaire_cerfa_remplis formulaire_cerfa_remplis VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE demande_changement_adresse CHANGE recto_verso_carte_grise recto_verso_carte_grise VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE demande_certificat_immatriculation demande_certificat_immatriculation VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE piece_identite_valid piece_identite_valid VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE copie_attestation_assurance_valide copie_attestation_assurance_valide VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE copie_permis_conduire copie_permis_conduire VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE justificatif_domicile justificatif_domicile VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE demande_ctvo CHANGE files_id files_id INT DEFAULT NULL, CHANGE recto_verso_carte_grise recto_verso_carte_grise VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE declatation_cession declatation_cession VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE demande_certificat demande_certificat VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE procuration_mandat procuration_mandat VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE piece_identite piece_identite VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE copie_controle_technique copie_controle_technique VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE recepisse_demande_achat recepisse_demande_achat VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE copie_attestation_assurance copie_attestation_assurance VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE copie_permis_conduire_titulaire copie_permis_conduire_titulaire VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE justificatif_domicile justificatif_domicile VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE demande_duplicata CHANGE recto_verso_carte_grise recto_verso_carte_grise VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE certificat_immatriculation certificat_immatriculation VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE declarationde_perte_ou_vol declarationde_perte_ou_vol VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE copie_controle_technique_en_cours_validite copie_controle_technique_en_cours_validite VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE piece_identite_valid piece_identite_valid VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE copie_attestation_assurance_valide copie_attestation_assurance_valide VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE permis_de_conduire_du_titulaire permis_de_conduire_du_titulaire VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE demande_ivn CHANGE original_certificat_conformite_europeen original_certificat_conformite_europeen VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE certificat_vente_original_facture_achat certificat_vente_original_facture_achat VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE piece_identite_valid piece_identite_valid VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE copie_attestation_assurance_valide copie_attestation_assurance_valide VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE copie_permis_conduire_titulaire copie_permis_conduire_titulaire VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE demande_original_certificat_immatriculation demande_original_certificat_immatriculation VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE procuration_par_mandat procuration_par_mandat VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE justificatif_domicile_recent justificatif_domicile_recent VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE divn CHANGE demande_id demande_id INT DEFAULT NULL, CHANGE acquerreur_id acquerreur_id INT DEFAULT NULL, CHANGE file_id file_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE documents CHANGE fichier_id fichier_id INT DEFAULT NULL, CHANGE type_demande_id type_demande_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE duplicata CHANGE titulaire_id titulaire_id INT DEFAULT NULL, CHANGE demande_id demande_id INT DEFAULT NULL, CHANGE file_id file_id INT DEFAULT NULL, CHANGE demande_changement_titulaire demande_changement_titulaire TINYINT(1) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE fichier CHANGE demande_id demande_id INT DEFAULT NULL, CHANGE client_id client_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE valide_le valide_le DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE files CHANGE demande_id demande_id INT DEFAULT NULL, CHANGE demande_duplicata_id demande_duplicata_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE financial_transactions CHANGE credit_id credit_id INT DEFAULT NULL, CHANGE payment_id payment_id INT DEFAULT NULL, CHANGE extended_data extended_data LONGTEXT DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci COMMENT \'(DC2Type:extended_payment_data)\', CHANGE reason_code reason_code VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE reference_number reference_number VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE response_code response_code VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE tracking_id tracking_id VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE fos_user CHANGE client_id client_id INT DEFAULT NULL, CHANGE salt salt VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE last_login last_login DATETIME DEFAULT \'NULL\', CHANGE confirmation_token confirmation_token VARCHAR(180) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE password_requested_at password_requested_at DATETIME DEFAULT \'NULL\', CHANGE register_date register_date DATETIME DEFAULT \'NULL\', CHANGE france_connect_id france_connect_id VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE history_transaction CHANGE demande_id demande_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE new_titulaire CHANGE type type VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE raison_sociale raison_sociale VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE societe_commerciale societe_commerciale TINYINT(1) DEFAULT \'NULL\', CHANGE siren siren VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE payment_instructions CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE payments CHANGE expiration_date expiration_date DATETIME DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE tarifs_prestations CHANGE commande_id commande_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE taxes CHANGE commande_id commande_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE transaction CHANGE demande_id demande_id INT DEFAULT NULL, CHANGE amount amount INT DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE transaction_id transaction_id VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE user_infos CHANGE cession_acheteur_id cession_acheteur_id INT DEFAULT NULL, CHANGE cession_vendeur_id cession_vendeur_id INT DEFAULT NULL, CHANGE adresse_id adresse_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE vehicule CHANGE vehicule_ancientitulaire_id vehicule_ancientitulaire_id INT DEFAULT NULL, CHANGE vehicule_cartegrise_id vehicule_cartegrise_id INT DEFAULT NULL, CHANGE vehicule_demande_id vehicule_demande_id INT DEFAULT NULL, CHANGE vehicule_client_id vehicule_client_id INT DEFAULT NULL, CHANGE client_id client_id INT DEFAULT NULL, CHANGE titulaire_id titulaire_id INT DEFAULT NULL, CHANGE numformule numformule VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE datecg datecg DATE DEFAULT \'NULL\'');
    }
}
